name: Github action to run tests
on: push
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "Install requirements"
        run: pip install -r requirements.txt
      - name: "Run tests"
        run: |
          export LD_PRELOAD=/lib/x86_64-linux-gnu/libstdc++.so.6:$LD_PRELOAD
          python -m pytest